### ISSUE TITLE
Pull in Elgg related activity from around the web

### ISSUE THREAD

**Issue by ewinslow** [Elgg/community_customizations#11]
Just thought it would be handy to if the community became a one stop shop for finding out what's happening with Elgg, but you can still have interactions elsewhere. E.g. any tweets that match `@elgg OR #elgg` could get pulled in as wire posts associated with a new site whose url is twitter.com. Closest parallel I can think of at the moment is what we're doing with blogs from blog.elgg.org.

But if we did this I'd want to do it right with better federation support, not just naively copying from sites into the community. Must have explicit modeling for remote users, remote objects, etc.

My vision is that actual interactions with these remote objects would happen on the source domain. So they're essentially read only. If updates to entity content happen, they have to happen via the remote service and it should be possible to sync those changes to the local "cache" in Elgg. If entity is deleted we should respect that, etc.

A humble start to distributed social networking...? :).

**Comment by juho-jaakkola** [comment]
Seems like that PR had a wrong issue number.

**Comment by beck24** [comment]
Oh I see what happened, the issue was reported as number 11 on the community_theme plugin.  Thanks Juho
