### ISSUE TITLE
email: Add name to From header

### ISSUE THREAD

**Issue by mrclay** [Elgg/community_customizations#12]
Instead of just `no-reply@elgg.org` something like `Elgg Community <no-reply@community.elgg.org>`

If this is awkward to do via the API we should make it easier in core.

**Comment by ewinslow** [comment]
+1 I was thinking even:

Paweł Srokap (via Elgg Community)

**Comment by Srokap** [comment]
@evan That looks nice, but there was some special SMTP for sending email as smb else but not being him. That would imply giving our user email, which is not necessairly best idea.

I think that proposed solution is acceptable, but could be better if we used stuff designed in protocol for such cases.

**Comment by ewinslow** [comment]
BTW I'm not `@evan` :)

**Comment by ewinslow** [comment]
on-behalf-of might be a good solution, but we still wouldn't want to expose the actual email.

**Comment by Srokap** [comment]
@ewinslow Ah, sorry. BTW I'm Sroka, not Srokap, but my mistake wasn't meant as any retaliation ;-)

I think that's generally field for plugins. If we wanted to implement replying via email, we could generate some addresses like `community-reply+{TOKEN}@elgg.org` and handle that (did something similar, fetching emails via IMAP. Gmail would redirect everything to community-reply@elgg.org as it does for all gmail accounts). Without that, it's more like 2 options: expose email or just do `Paweł Sroka (via Elgg Community)`

**Comment by mrclay** [comment]
I think "Elgg Community (Pawel Sroka)" would make mail client sorting easier. But really mail apps tend to show the first line of the body (which has the username) anyway.

**Comment by ewinslow** [comment]
I'm fine with that suggestion too.
