### ISSUE TITLE
User doesn't get forwarded back to topic after using "You must log in to post replies"

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/community_customizations#14]
Non-logged in users have the "You must **log in** to post replies" text at the bottom of discussion replies. When user signs in using it, they get forwarded to front page instead of the discussion.

We should probably just update `$_SESSION['last_forward_from']` every time the link is printed.

**Comment by mrclay** [comment]
Changing user state on GET: I'm against it. Not a caching-friendly solution, and someday we'll ideally have no active session when logged out

**Comment by juho-jaakkola** [comment]
Do we have other options?
