### ISSUE TITLE
Questions and answers

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/community_customizations#8]
This issue should maybe belong into it's own plugin but I'll add it here for now.

The current community discussions feature often leads into long conversations which easily get off track or become chats between a couple of users.

Let's add a "Questions and answers" feature (similar to http://stackoverflow.com/) that directs users to giving comprehensive and well argumented answers instead of posting multiple unrelated and unhelpful comments.

Features: 
- Community members could upvote and downvote the answers
- Answers with enough downvotes would be hidden/removed automatically
- It would be easy to add functionality described in #4 
- The question add form would direct user into forming a good question
  - Instructions on how to ask a good question
  - Which Elgg version they are using
  - URL to the plugin they have a question about
  - etc...

**Comment by Srokap** [comment]
Good idea. I was thinking before about some tool to organize existing discussion posts, but didn't solve the problem of poor content. The idea was to organize existing topics in a FAQ section.  Making separate tool is probably the best way to address it.

According to question form, I think most of these should be optional with strong suggestion that filling it will allow to get help faster. Some question may be not bound to specific version and users might be able to provide external site URL, but that's not always the case, so in general, form should be optional.

**Comment by brettp** [comment]
I've ported and developed a few for different clients. I can ask if they will GPL the code.
